version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_HEAP} -Xmx${ES_HEAP}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${DATA_DIRECTORY}/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
    restart: on-failure:5

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      NGINX_DOMAIN: jivesearch.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DATA_DIRECTORY}/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    restart: on-failure:5
    network_mode: host

  nsfw:
    build: ./nsfw
    container_name: nsfw
    ports:
     - 8080:8080
    restart: on-failure:5

  # NOTE: If you change your POSTGRES_USER then run "sudo docker-compose rm"
  # https://github.com/docker-library/postgres/issues/41#issuecomment-167603905
  # To access psql -> docker exec -ti postgres psql -U jivesearch
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: jivesearch
      POSTGRES_DB: jivesearch
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5432:5432
    volumes:
      - ${DATA_DIRECTORY}/postgresql:/var/lib/postgresql/data
    restart: on-failure:5
  
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: on-failure:5

networks:
  esnet: